const products =[
    {     
        id:1,
        nombre:"samsung s 10",
        precio:1000,
        cantidad:1,
        category:'Samsung',
        img:'../public/images/samsungs10.png',
    },
    {
        id:2,
        nombre:"samsung s 20",
        precio:1100,
        cantidad:1,
        category:'Samsung',
        img:"../public/images/samsungs20.png",
    },
    {
        id:3,
        nombre:"samsung s 21",
        precio:1200,
        cantidad:1,
        category:'Samsung',
        img:"../public/images/samsungs21.png",
    },
    {
        id:4,
        nombre:"samsung s 22",
        precio:1300,
        cantidad:1,
        category:'Samsung',
        img:"../public/images/samsungs22.png",
    },
    {
        id:5,
        nombre:"samsung s 23",
        precio:1400,
        cantidad:1,
        category:'Samsung',
        img:"../public/images/samsungs23.png",
    },
    {
        id:6,
        nombre:"samsung s 24",
        precio:1500,
        cantidad:1,
        category:'Samsung',
        img:"../public/images/samsungs24.png",
    },
    {
        id:7,
        nombre:"xiaomi red mi 9",
        precio:1000,
        cantidad:1,
        category:'Xiaomi',
        img:"../public/images/xiaomiredminote9.jpg",
    },
    {
        id:8,
        nombre:"xiaomi red mi 10",
        precio:1050,
        cantidad:1,
        category:'Xiaomi',
        img:"../public/images/xiaomiredminote10.jpg",
    },
    {
        id:9,
        nombre:"xiaomi red mi 11",
        precio:1100,
        cantidad:1,
        category:'Xiaomi',
        img:"../public/images/xiaomiredminote11.jpg",
    },
    {
        id:10,
        nombre:"xiaomi red mi 12",
        precio:1150,
        cantidad:1,
        category:'Xiaomi',
        img:"../public/images/xiaomiredminote12.jpg",
    },
    {
        id:11,
        nombre:"xiaomi red mi 13",
        precio:1200,
        cantidad:1,
        category:'Xiaomi',
        img:"../public/images/xiaomiredminote13.jpg",
    },
    {
        id:12,
        nombre:"iphone 11",
        precio:1200,
        cantidad:1,
        category:'Iphone',
        img:"../public/images/iphone11.jpg",
    },
    {
        id:13,
        nombre:"iphone 12",
        precio:1300,
        cantidad:1,
        category:'Iphone',
        img:"../public/images/iphone12.jpg",
    },
    {
        id:14,
        nombre:"iphone 13",
        precio:1400,
        cantidad:1,
        category:'Iphone',
        img:"../public/images/iphone13.jpg",
    },
    {
        id:15,
        nombre:"iphone 14",
        precio:1500,
        cantidad:1,
        category:'Iphone',
        img:"../public/images/iphone14.jpg",
    },
    {
        id:16,
        nombre:"iphone 15",
        precio:1600,
        cantidad:1,
        category:'Iphone',
        img:"../public/images/iphone15.jpg",
    },
    {
        id:17,
        nombre:"moto g 21",
        precio:800,
        cantidad:1,
        category:'Motorola',
        img:"../public/images/motorolag21.png",
    },
    {
        id:18,
        nombre:"moto g 22",
        precio:850,
        cantidad:1,
        category:'Motorola',
        img:"../public/images/motorolag22.png",
    },
    {
        id:19,
        nombre:"moto g 23",
        precio:900,
        cantidad:1,
        category:'Motorola',
        img:"../public/images/motorolag23.png",
    },
    {
        id:20,
        nombre:"moto g 24",
        precio:1000,
        cantidad:1,
        category:'Motorola',
        img:"../public/images/motorolag24.png",
    },
    {
        id:21,
        nombre:"moto g 74",
        precio:1100,
        cantidad:1,
        category:'Motorola',
        img:"../public/images/motorolag74.png",
    },
];

export const getProducts = new Promise((resolve) => {
    setTimeout(() =>{
        resolve(products);
    }, 1000);
});
export const getProduct = (id) =>{
    return products.find((prod) =>prod.id == id);
};
export const getCategory = (categoryId) => {
    return products.filter((product)=> product.category === categoryId)
}
